---

- hosts: all
  become: true
  vars:
    install_requirements: true
    install_ohmyzsh: true
    install_php: true
    install_composertools: true
    install_mysql: true
    install_apache: true
    install_nodejs: true
    composer_path: /usr/local/bin/composer
    local_composer: /home/vagrant/.config/composer/vendor/bin/
    sites: [
        { hostname: 'app.local', document_root: '/var/www/html' },
        { hostname: 'test.local', document_root: '/var/www/test' }
    ]
    zsh_theme: kardan
    zsh_dir: /home/vagrant/.oh-my-zsh
    databases: ['database']
    nodejs_version: "10.x"
    nodejs_install_npm_user: "{{ ansible_ssh_user }}"
    npm_config_prefix: "/usr/local/lib/npm"
    npm_config_unsafe_perm: "false"
    nodejs_npm_global_packages: []

  tasks:
    - import_tasks: ./local-env/tasks/requirements.yml
      when: install_requirements == true
      
    - import_tasks: ./local-env/tasks/ohmyzsh.yml
      when: install_ohmyzsh == true

    - import_tasks: ./local-env/tasks/php.yml
      when: install_php == true

    - import_tasks: ./local-env/tasks/composertools.yml
      when: install_composertools == true

    - import_tasks: ./local-env/tasks/mysql.yml
      when: install_mysql == true

    - import_tasks: ./local-env/tasks/apache.yml
      when: install_apache == true

    - import_tasks: ./local-env/tasks/nodejs.yml
      when: install_nodejs == true

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
    - name: restart apache2
      service: name=apache2 state=restarted
