---

- name: OhMyZsh -> Registrating ohmyzsh template path
  stat: path={{ zsh_dir }}
  register: ohmyzsh_template

- name: OhMyZsh -> Registrating ohmyzsh rc path
  stat: path=/home/vagrant/.zshrc
  register: ohmyzsh_rc

- name: OhMyZsh -> Installing zsh
  apt: 
    name: zsh 
    state: present

- name: OhMyZsh -> Configuring oh-my-zsh
  git:
    repo: 'https://github.com/robbyrussell/oh-my-zsh.git'
    dest: "{{ zsh_dir }}"
  when: ohmyzsh_template.stat.exists == False

- name: OhMyZsh -> Clonning zsh-syntax highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "{{ zsh_dir }}/plugins/zsh-syntax-highlighting"

- name: OhMyZsh -> Installing ruby-full
  apt: pkg=ruby-full state=present

# - name: OhMyZsh -> Clonning fonts
#   git:
#     repo: https://github.com/ryanoasis/nerd-fonts.git
#     dest: /tmp/nerd-fonts

# - name: OhMyZsh -> Installing Fonts
#   shell: sh /tmp/nerd-fonts/install.sh

- name: OhMyZsh -> Configuring default theme from Oh my zsh
  template: src=../config/.zshrc dest=/home/vagrant/.zshrc
  # when: ohmyzsh_rc.stat.exists == False

- name: OhMyZsh -> Installing colors
  shell: gem install colorls

- name: OhMyZsh -> Change default bash
  user:
    force: true
    name: vagrant
    shell: /bin/zsh