---

- name: PHP -> Install Ondrej PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: yes
- name: PHP -> Install PHP Modules
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php7.2
    - libapache2-mod-php7.2
    - libargon2-0
    - libsodium23
    - libssl1.1
    - php7.2-cli
    - php7.2-common
    - php7.2-json
    - php7.2-opcache
    - php7.2-readline
    - php-pear 
    - php7.2-curl 
    - php7.2-dev 
    - php7.2-gd 
    - php7.2-mbstring 
    - php7.2-zip 
    - php7.2-mysql 
    - php7.2-xml

- name: PHP -> Conguring composer path
  stat: path={{composer_path}}
  register: composer_folder

- name: PHP -> Install Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp
    mode: 0440
- name: PHP -> Install Composer
  shell: php /tmp/installer && mv composer.phar {{composer_path}} creates={{composer_path}}
  when: composer_folder.stat.isdir is not defined